#!/bin/bash

# Check for proper number of arguments
if [ "$#" -lt 2 ] || [ "$#" -gt 5 ]; then
  echo "usage: clientStart <port1> <port2> [<port3> <port4>] [<delay>]"
  exit 1
fi

# Make sure you actually type in numbers
re='^[0-9]+$'
if ! [[ $1 =~ $re ]] || ! [[ $2 =~ $re ]] ; then
  echo "Error: non-integer value found"
  exit 1
fi

# Check delay for two players
if [ "$#" -eq 3 ]; then
  if ! [[ $3 =~ $re ]]; then
    echo "Error: invalid delay"
    exit 1
  fi
fi

# Check 3rd and 4th argument if exists as well as delay
if [ "$#" -ge 4 ]; then
  if ! [[ $3 =~ $re ]] || ! [[ $4 =~ $re ]] ; then
    echo "Error: non-integer value found"
    exit 1
  fi
  if [ "$#" -eq 5 ]; then
    if ! [[ $5 =~ $re ]]; then
      echo "Error: invalid delay"
      exit 1
    fi
  fi
fi

# Keep port numbers in proper range
if [ "$1" -le 1024 ] || [ "$2" -le 1024 ]; then
  echo "Error: Port numbers must be above 1024"
  exit 1
fi

# Check 3rd and 4th
if [ "$#" -ge 4 ]; then
  if [ "$3" -le 1024 ] || [ "$4" -le 1024 ]; then
    echo "Error: Port numbers must be above 1024"
    exit 1
  fi
fi

# Cannot use same port numbers
if [ "$#" -eq 2 ] || [ "$#" -eq 3 ]; then
  if [ "$1" -eq "$2" ]; then
    echo "Error: same port number detected"
    exit 1
  fi
  echo "Running 2 player"
  if [ "$#" -eq 2 ]; then
    java -cp build/libs/Quoridor-all.jar GameClient localhost:$1 localhost:$2
    exit 0
  else
    java -cp build/libs/Quoridor-all.jar GameClient --delay $3 localhost:$1 localhost:$2
    exit 0
  fi
fi

# Check 4 ports
ck=0
size=$#
if [ "$size" -eq 4 ] || [ "$size" -eq 5 ]; then
  p1=$1 p2=$2 p3=$3 p4=$4 p5=$5
  #set -- $1 $2 $3 $4
  for a; do
    shift
    for b; do
      if [ "$a" -eq "$b" ]; then
        ck=$(( $ck + 1 ))
      fi
    done
  done
  if [ "$ck" -ne 0 ]; then
    echo "Error: Same port number detected"
    exit 1
  fi
  echo "Running 4 player"
  if [ "$size" -eq 4 ]; then
    java -cp build/libs/Quoridor-all.jar GameClient localhost:$p1 localhost:$p2 localhost:$p3 localhost:$p4
    exit 0
  else
    java -cp build/libs/Quoridor-all.jar GameClient --delay $p5 localhost:$p1 localhost:$p2 localhost:$p3 localhost:$p4
    exit 0
  fi
fi
