#!/bin/bash

# Give 2 port number on command line to run
if [ "$#" -ne 2 ] && [ "$#" -ne 4 ]; then
  echo "usage: clientStart <port1> <port2> [<port3> <port4>]"
  exit 1
fi

# Make sure you actually type in numbers
re='^[0-9]+$'
if ! [[ $1 =~ $re ]] || ! [[ $2 =~ $re ]] ; then
  echo "Error: non-integer value found"
  exit 1
fi

# Check 3rd and 4th argument if exists
if [ "$#" -eq 4 ]; then
  if ! [[ $3 =~ $re ]] || ! [[ $4 =~ $re ]] ; then
    echo "Error: non-integer value found"
    exit 1
  fi
fi

# Keep port numbers in proper range
if [ "$1" -le 1024 ] || [ "$2" -le 1024 ]; then
  echo "Error: Port numbers must be above 1024"
  exit 1
fi

# Check 3rd and 4th
if [ "$#" -eq 4 ]; then
  if [ "$3" -le 1024 ] || [ "$4" -le 1024 ]; then
    echo "Error: Port numbers must be above 1024"
    exit 1
  fi
fi

# Cannot use same port numbers
if [ "$#" -eq 2 ]; then
  if [ "$1" -eq "$2" ]; then
    echo "Error: same port number detected"
    exit 1
  fi
  echo "Running 2 player"
  java -cp build/libs/Quoridor-all.jar GameClient localhost:$1 localhost:$2
  exit 0
fi

# Check 4 ports
ck=0
if [ "$#" -eq 4 ]; then
  p1=$1 p2=$2 p3=$3 p4=$4
  #set -- $1 $2 $3 $4
  for a; do
    shift
    for b; do
      if [ "$a" -eq "$b" ]; then
        ck=$(( $ck + 1 ))
      fi
    done
  done
  if [ "$ck" -ne 0 ]; then
    echo "Error: Same port number detected"
    exit 1
  fi
  echo "Running 4 player"
  java -cp build/libs/Quoridor-all.jar GameClient localhost:$p1 localhost:$p2 localhost:$p3 localhost:$p4
  exit 0
fi
