#!/bin/bash

# Give 2 port number on command line to run
if [ "$#" -ne 2 ]; then
  echo "usage: run2 <port1> <port2>"
  exit 1
fi

# Make sure you actually type in numbers
re='^[0-9]+$'
if ! [[ $1 =~ $re ]] || ! [[ $2 =~ $re ]] ; then
  echo "Error: non-integer value found"
  exit 1
fi

# Keep port numbers in proper range
if [ "$1" -le 1024 ] || [ "$2" -le 1024 ]; then
  echo "Error: Port numbers must be above 1024"
  exit 1
fi

# Cannot use same port number for both servers
if [ "$1" -eq "$2" ]; then
  echo "Error: same port number detected"
  exit 1
fi

# Launch servers in own terminals
gnome-terminal -e "./serverStart $1" &
gnome-terminal -e "./serverStart $2" &

# Wait for servers to start. (Thank you hivemind for the idea)
sleep 1;

# Launch client
./clientStart $1 $2
