#!/bin/bash

# Give 2 port number on command line to run
if [ "$#" -ne 2 ]; then
  echo "usage: run2 <port1> <port2>"
  exit 1
fi

# Make sure you actually type in numbers
re='^[0-9]+$'
if ! [[ $1 =~ $re ]] || ! [[ $2 =~ $re ]] ; then
  echo "Error: non-integer value found"
  exit 1
fi

# Keep port numbers in proper range
if [ "$1" -lt 2000 ] || [ "$2" -lt 2000 ] ; then
  echo "Error: Try to keep port numbers above 2000"
  exit 1
fi

# Cannot use same port number for both servers
if [ "$1" -eq "$2" ]; then
  echo "Error: same port number detected"
  exit 1
fi

# Launch servers when it has a main -- using netcat for now
nc -l $1 & nc -l $2 &

# Wait for servers to start. (Thank you hivemind for the idea)
sleep 1;

# Launch client
java -cp build/libs/Quoridor.jar GameClient localhost:$1 localhost:$2
