#!/bin/bash

# Give 4 port number on command line to run
if [ "$#" -ne 4 ]; then
  echo "usage: run2 <port1> <port2> <port3> <port4>"
  exit 1
fi

# Make sure you actually type in numbers
re='^[0-9]+$'
if ! [[ $1 =~ $re ]] || ! [[ $2 =~ $re ]] || ! [[ $3 =~ $re ]] || ! [[ $4 =~ $re ]]; then
  echo "Error: non-integer value found"
  exit 1
fi

# Keep port numbers in proper range
if [ "$1" -le 1024 ] || [ "$2" -le 1024 ] || [ "$3" -le 1024 ] || [ "$4" -le 1024 ]; then
  echo "Error: Port numbers must be above 1024"
  exit 1
fi

p1=$1 p2=$2 p3=$3 p4=$4

# Check 4 ports
ck=0
for a; do
  shift
  for b; do
    if [ "$a" -eq "$b" ]; then
      ck=$(( $ck + 1 ))
    fi
  done
done
if [ "$ck" -ne 0 ]; then
  echo "Error: Same port number detected"
  exit 1
fi

# Launch servers in own terminals
xterm -e "./serverStart $p1" &
xterm -e "./serverStart $p2" &
xterm -e "./serverStart $p3" &
xterm -e "./serverStart $p4" &

# Wait for servers to start. (Thank you hivemind for the idea)
sleep 1;

# Launch client
./clientStart $p1 $p2 $p3 $p4
